### ISSUE TITLE
Content Missing

### ISSUE THREAD

**Issue by Arunpradeepan** [jure/mathtype#4]
[rId12.zip](https://github.com/jure/mathtype/files/2419755/rId12.zip)

Thanks for your wonderful product.

I am try with attach bin. some content missing in mathml.
prod above 'n' character missing in the output.
Please guide me or update the mathtype

**Comment by sbulka** [comment]
Hi,

this gem does not produce mathml by itself.

I converted your file with this XProc step (which uses the mathtype gem): https://github.com/transpect/mathtype-extension
The generated MathML contains the 'n' above the Product.
This gem was used to produce "02-mtef2xml.xml".

[rId12-mml.zip](https://github.com/jure/mathtype/files/2419976/rId12-mml.zip)

If you need further help generating MathML from the gem's xml, please contact the other project's support/maintainer.
